config/routes.rb
Rails.application.routes.draw do
  get 'comment/body'
  resources :events do
    end
  #resources :comments, only: [:create, :index, :destroy]
  get 'login/index'
  resources :registers
  resources :reports
  resources :events
  resources :home
  
  #root 'users#index'
  #root 'events#index'
  #root 'reports#index'
  root 'events#index'
  #root 'registers#index'
  get 'static' => 'static_pages#static'
  get 'howto' => 'static_pages#howto'
  get  'about' => 'static_pages#about'
  get  'contact'  => 'static_pages#contact'
  get  'homepage'  => 'static_pages#homepage'
  #get 'users/index'
  #get 'events/index'
  #get 'reports/index'
  #get 'login/index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'registers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'homeevent', to: 'static_pages#homepage', as: 'homeevent'
  get 'back', to: 'static_pages#static', as: 'back'
  get 'account', to: 'home#index', as: 'account'

end

app/models/register.rb
class Register < ApplicationRecord
    has_secure_password
    has_many :comments, dependent: :destroy
    #has_many :events, :through => :comments
    validates :email, uniqueness: true,format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
    validates :password, presence: true
    validates :password_confirmation, presence: true
    validates :username, uniqueness: true
    validates :phone, presence: true , format: { with: /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/ } 
    mount_uploader :image, ImageUploader 
  
    
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :authenticate_admin!, only: [:show,:destroy]
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
    
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:email, :username, :password, :password_confirmation, :phone,:image)
    end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<p id="alert"><%= alert %></p>
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <a href = login><h2 class="inactive underlineHover"> Sign In </h2></a>
    <a href = registers/new><h2 class="active">Sign Up </h2></a>

    <!-- Icon -->
    <div class="fadeIn first">
      <%= image_tag("user(1).png", :id => "icon2") %>
    </div>

    <%= form_for @register do |f| %>
      <% if @register.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= "#{pluralize(@register.errors.count, "error")} prohibited this register from being saved:" %>
          </h2>
          <ul>
            <% @register.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class=" fadeIn second field">
          <%= f.text_field :username, required: true, placeholder: "Username" %>
      </div>
      <div class=" fadeIn third field">
          <%= f.text_field :email, required: true, placeholder: "E-mail" %>
      </div>
      <div class=" fadeIn third field">
          <%= f.password_field :password, required: true, placeholder: "Passowrd" %>
      </div>
      <div class=" fadeIn third field">
          <%= f.password_field :password_confirmation, required: true, placeholder: "Password confirmation" %>
      </div>
      <div class=" fadeIn third field">
          <%= f.text_field :phone, autofocus: true, required: true, placeholder: "Phone" %>
      </div>
      <div class="actions">
          <%= submit_tag "JOIN NOW",:class =>"fadeIn fourth" %> 
      </div>
    <% end %>
  </div>
</div>

app/views/registers/edit.html.erb
%h1 Editing register

= render 'form'

= link_to 'Show', @register

/*= link_to 'Back', registers_path
= link_to 'Back', homeevent_path
/*= link_to 'Home', controller: "static_pages", action: "static"

app/views/registers/index.html.haml
%h1 Listing registers

%table
  %thead
    %tr
      %th Email
      %th Username
      %th Phone
      %th Image
      %th
      %th
      %th

  %tbody
    - @registers.each do |register|
      %tr
        %td= register.email
        %td= register.username
        %td= register.phone
        %td= image_tag register.image_url.to_s,style:"height: 100px; width: 100px;"
        %td= link_to 'Show', register
        %td= link_to 'Edit', edit_register_path(register)
        %td= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Register', new_register_path

= link_to 'back', root_url

app/views/registers/new.html.haml
= render 'form'


/*= link_to 'Back', controller: "static_pages", action: "static"

app/views/registers/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @register.email
%p
  %b Username:
  = @register.username

%p
  %b Phone:
  = @register.phone

= link_to 'Edit', edit_register_path(@register)

= link_to 'Back', homeevent_path

/*= link_to 'Home', controller: "static_pages", action: "static"

app/views/registers/test.html.erb
<html>
  <head>
    <title> Account </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'registers', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'registers', 'data-turbolinks-track': 'reload' %>
    
    <script>
        document.querySelector('.img__btn').addEventListener('click', function() {
        document.querySelector('.cont').classList.toggle('s--signup');});
    </script>
  </head>
  <body>
            <div class="cont">
              <div class="form sign-in">
                <h2>Welcome back,</h2>
                <label>
                  <span>Email</span>
                  <input type="email" />
                </label>
                <label>
                  <span>Password</span>
                  <input type="password" />
                </label>
                <p class="forgot-pass">Forgot password?</p>
                <button type="button" class="submit">Sign In</button>
                <button type="button" class="fb-btn">Connect with <span>facebook</span></button>
              </div>
              <div class="sub-cont">
                <div class="img">
                  <div class="img__text m--up">
                    <h2>New here?</h2>
                    <p>Sign up and discover great amount of new opportunities!</p>
                  </div>
                  <div class="img__text m--in">
                    <h2>One of us?</h2>
                    <p>If you already has an account, just sign in. We've missed you!</p>
                  </div>
                  <div class="img__btn">
                    <span class="m--up">Sign Up</span>
                    <span class="m--in">Sign In</span>
                  </div>
                </div>
                <div class="form sign-up">
                  <h2>Time to feel like home,</h2>
                  <label>
                    <span>Name</span>
                    <input type="text" />
                  </label>
                  <label>
                    <span>Email</span>
                    <input type="email" />
                  </label>
                  <label>
                    <span>Password</span>
                    <input type="password" />
                  </label>
                  <button type="button" class="submit">Sign Up</button>
                  <button type="button" class="fb-btn">Join with <span>facebook</span></button>
                </div>
              </div>
            </div>
            
            <a href="https://dribbble.com/shots/3306190-Login-Registration-form" target="_blank" class="icon-link">
              <img src="http://icons.iconarchive.com/icons/uiconstock/socialmedia/256/Dribbble-icon.png">
            </a>
            <a href="https://twitter.com/NikolayTalanov" target="_blank" class="icon-link icon-link--twitter">
              <img src="https://cdn1.iconfinder.com/data/icons/logotypes/32/twitter-128.png">
            </a>
</body>
</html>