config/routes.rb
Rails.application.routes.draw do
  get 'comment/body'
  resources :events do
    end
  #resources :comments, only: [:create, :index, :destroy]
  get 'login/index'
  resources :registers
  resources :reports
  resources :events
  resources :home
  
  #root 'users#index'
  #root 'events#index'
  #root 'reports#index'
  root 'events#index'
  #root 'registers#index'
  get 'static' => 'static_pages#static'
  get 'howto' => 'static_pages#howto'
  get  'about' => 'static_pages#about'
  get  'contact'  => 'static_pages#contact'
  get  'homepage'  => 'static_pages#homepage'
  #get 'users/index'
  #get 'events/index'
  #get 'reports/index'
  #get 'login/index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'registers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'homeevent', to: 'static_pages#homepage', as: 'homeevent'
  get 'back', to: 'static_pages#static', as: 'back'
  get 'account', to: 'home#index', as: 'account'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<html>
  <head>
    <title> Account </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
  </head>
  <body>
      <p id="notice"><%= notice %></p>
          <% if current_user %>
            <div class="center">
              <p class="font">General Account Settings</p><br><br>
                <%= image_tag current_user.image_url.to_s,style:"height: 100px; width: 100px;" %><br>
                Username : <%= current_user.username %><br>
                Email    : <%= current_user.email %><br>
                Phone    : <%= current_user.phone %><br>
                <%= link_to "Log Out", logout_path %>
                <%= link_to "Destroy",current_user, method: :delete, data: { confirm: 'Are you sure?' } %>
                <%= link_to "Edit", edit_register_path(current_user) %>
                <%= link_to "Back", homeevent_path %>
            </div>
          <% else %>
            <%= link_to "Sign Up", signup_path  %> or
            <%= link_to "Log In", login_path %>
          <% end %>

  </body>

</html>