config/routes.rb
Rails.application.routes.draw do
  get 'comment/body'
  resources :events do
    end
  #resources :comments, only: [:create, :index, :destroy]
  get 'login/index'
  resources :registers
  resources :reports
  resources :events
  resources :home
  
  #root 'users#index'
  #root 'events#index'
  #root 'reports#index'
  root 'events#index'
  #root 'registers#index'
  get 'static' => 'static_pages#static'
  get 'howto' => 'static_pages#howto'
  get  'about' => 'static_pages#about'
  get  'contact'  => 'static_pages#contact'
  get  'homepage'  => 'static_pages#homepage'
  #get 'users/index'
  #get 'events/index'
  #get 'reports/index'
  #get 'login/index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'registers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'homeevent', to: 'static_pages#homepage', as: 'homeevent'
  get 'back', to: 'static_pages#static', as: 'back'
  get 'account', to: 'home#index', as: 'account'

end

app/models/event.rb
class Event < ApplicationRecord
    has_many :comments,dependent: :destroy
    validates :title, presence: true
    validates :category, presence: true
    validates :description, presence: true
    validates :phone, presence: true 
  


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order("created_at DESC")
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @events = Event.all

  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event } #, notice: 'Event was successfully updated.'
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :category, :description, :by ,:start, :end, :phone)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :category
    = f.select :category,['food','concert','movie','sport','travel','game','university','Etc.']
  .field
    = f.label :description
    = f.text_area :description , maxlength: 255, size: 15
  .field
    = f.label :by
    = f.text_field :by
  .field
    = f.label :start
    = f.date_select :start
  .field
    = f.label :end
    = f.date_select  :end
  .field
    = f.label :phone
    = f.text_field :phone
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
= link_to 'Back', events_path
/*= link_to 'Back',homeevent_path

app/views/events/index.html.erb
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet"> 

  </head>
  <body>
    <% @events.each do |event| %>
  <div class="link row clearfix font">
    <h2>
      <div >
        <%= link_to event.title, event %>
        #<%= event.category %><br><br>
      </div>
    </h2>
  </div>
  <% end %>
  </body>
</html>

app/views/events/new.html.haml
= render 'form'

/*= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Category:
  = @event.category
%p
  %b Description:
  = @event.description
%p
  %b By:
  = @event.by
%p
  %b Start:
  = @event.start
%p
  %b End:
  = @event.end
%p
  %b Phone:
  = @event.phone
 


//= link_to 'Add Comment', new_event_comment_path(@event)
= link_to 'Edit', edit_event_path(@event)
= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }
/*= link_to 'Back', events_path
= link_to 'Back',homeevent_path