config/routes.rb
Rails.application.routes.draw do
  get 'comment/body'
  resources :events do
    end
  #resources :comments, only: [:create, :index, :destroy]
  get 'login/index'
  resources :registers
  resources :reports
  resources :events
  resources :home
  
  #root 'users#index'
  #root 'events#index'
  #root 'reports#index'
  root 'events#index'
  #root 'registers#index'
  get 'static' => 'static_pages#static'
  get 'howto' => 'static_pages#howto'
  get  'about' => 'static_pages#about'
  get  'contact'  => 'static_pages#contact'
  get  'homepage'  => 'static_pages#homepage'
  #get 'users/index'
  #get 'events/index'
  #get 'reports/index'
  #get 'login/index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'registers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'homeevent', to: 'static_pages#homepage', as: 'homeevent'
  get 'back', to: 'static_pages#static', as: 'back'
  get 'account', to: 'home#index', as: 'account'

end

app/models/report.rb
class Report < ApplicationRecord
     validates :event, presence: true
     validates :report_to, presence: true
     validates :by, presence: true
     validates :desciption, presence: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:event,:report_to,:by,:desciption)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= form_for @report do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :event
    = f.text_field :event
  .field
    = f.label :report_to
    = f.text_field :report_to
  .field
    = f.label :by
    = f.text_field :by
  .field
    = f.label :desciption
    = f.text_area :desciption,:cols => 70, :rows => 20
  .actions
    = f.submit 'Save'

app/views/reports/edit.html.haml
%h1 Editing report

= render 'form'

= link_to 'Show', @report

/*= link_to 'Back', reports_path*/
= link_to 'Back',homeevent_path

app/views/reports/index.html.haml
%h1 Reports users

%table
  %thead
    %tr
      %th Event
      %th Report To
      %th By
      %th Desciption
      %th
      %th
      %th
  %tbody
    - @reports.each do |report|
      %tr
        %td= report.event
        %td= report.report_to
        %td= report.by
        %td= report.desciption
        %td= link_to 'Show', report
        %td= link_to 'Edit', edit_report_path(report)
        %td= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Report', new_report_path
= link_to 'Back', root_url

app/views/reports/new.html.haml
%h1 New report

= render 'form'

/*= link_to 'Back', reports_path

= link_to 'Back', homeevent_path

app/views/reports/show.html.haml
%p#notice= notice

%p
  %b Event:
  = @report.event
%p
  %b Report To:
  = @report.report_to
%p
  %b By:
  = @report.by
%p
  %b Desciption:
  = @report.desciption

= link_to 'Edit', edit_report_path(@report)
= link_to 'Destroy', @report, method: :delete, data: { confirm: 'Are you sure?' }
/*= link_to 'Back', reports_path*/

= link_to 'Back', homeevent_path